<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <RootNamespace></RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <Import Include="System.Drawing" />
        <Import Include="System.Windows.Forms" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Form1.Designer.vb">
            <DependentUpon>Form1.vb</DependentUpon>
        </Compile>
        <Compile Update="My Project\Resources.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="My Project\Settings.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
        </Compile>
        <None Update="Templates\Detail.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Master.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Templates\Template.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="nwind.xml">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="DevExpress.Win.RichEdit" Version="24.2.*-*" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="Pictures\1.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\2.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\3.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\5.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\4.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\6.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\7.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="Pictures\8.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>